crs4/DigitalPathologyPlatform

.gitignore
promort/promort/settings.py
promort/promort/urls.py
promort/reviews_manager/migrations/0001_initial.py
promort/reviews_manager/migrations/0002_auto_20160622_0917.py
promort/reviews_manager/models.py
promort/reviews_manager/permissions.py
promort/reviews_manager/serializers.py
promort/reviews_manager/views.py
promort/slides_manager/migrations/0001_initial.py
promort/slides_manager/models.py
promort/slides_manager/serializers.py
promort/slides_manager/views.py
promort/view_templates/views.py
requirements.txt
requirements_server.txt
requirements_tools.txt

Added models and methods to define and manage reviews  and review steps.

Reviews manager

---

promort/authentication/serializers.py
promort/authentication/views.py
promort/promort/settings.py
promort/promort/urls.py
promort/worklist_manager/migrations/0001_initial.py
promort/worklist_manager/views.py
tools/clear_db.py
tools/import_slides.py

Added HTTP methods to handle work lists for the reviewers.
Cases and slides importer now automatically create and assigns reviews and review steps to reviewers that belong to the 1st reviewers group.

Worklist manager

---

promort/static/css/promort.css
promort/static/templates/annotation_manager/annotation_manager.html
promort/static/templates/annotation_manager/buttons_ctrl_group.html
promort/static/templates/annotation_manager/core_annotation.html
promort/static/templates/annotation_manager/generic_form_template.html
promort/static/templates/annotation_manager/region_annotation.html
promort/static/templates/annotation_manager/slice_annotation.html

Templates to be used with Angular.js for annotations manager section

Templates for annotations manager

---

promort/promort/settings.py
promort/promort/urls.py
promort/rois_manager/migrations/0001_initial.py
promort/rois_manager/migrations/0002_auto_20160718_1325.py
promort/rois_manager/migrations/0003_auto_20160913_1318.py
promort/rois_manager/migrations/0004_auto_20160914_0848.py
promort/rois_manager/migrations/0005_auto_20160914_1418.py
promort/rois_manager/models.py
promort/rois_manager/serializers.py
promort/rois_manager/views.py
promort/view_templates/views.py

Backend to manage Regions of Interests such as Slices, Cores and Focus Regions

ROIs backend

---

promort/rois_manager/migrations/0008_core_tumor_length.py
promort/rois_manager/models.py
promort/rois_manager/serializers.py
promort/slides_manager/migrations/0006_slidequalitycontrol_notes.py
promort/slides_manager/models.py
promort/slides_manager/serializers.py
promort/src/js/ome_seadragon_viewer/viewer.directives.js
promort/src/js/rois_manager/rois_manager.controllers.js
promort/src/js/rois_manager/rois_manager.services.js
promort/src/js/slides_manager/slides_manager.controllers.js
promort/src/js/slides_manager/slides_manager.services.js
promort/static/css/promort.css
promort/static/templates/authentication/login.html
promort/static/templates/index/index.html
promort/static/templates/rois_manager/core.html
promort/static/templates/rois_manager/manager.html
promort/static/templates/slide_review/quality_control.html
promort/static/templates/viewer/rois_viewer.html
promort/static/templates/worklist/pending_reviews.html
promort/static/templates/worklist/review_steps.html
promort/templates/index.html

These enhancements require ome_seadragon >= 0.5.5

A few enhancements for v0.1.0-alpha-2

---

promort/static/templates/annotation_manager/annotation_manager.html
promort/static/templates/annotation_manager/buttons_ctrl_group.html
promort/static/templates/annotation_manager/core_annotation.html
promort/static/templates/annotation_manager/region_annotation.html
promort/static/templates/annotation_manager/slice_annotation.html

Clinical annotation layout updated

Clinical annotation layout

---

.gitignore
promort/logs/.gitignore
promort/reviews_manager/management/commands/clean_annotations.py

The command will clean:
- related clinical annotation steps data (slice, core and focus region annotations)
- related ROIs (slice, cores and focus regions)
- set ROIs annotation step as brand new (erase start and completion timestamps)

Added command to clean ROIs annotation step related data

---

promort/reviews_manager/views.py
promort/src/js/clinical_annotations_manager/clinical_annotations_manager.controllers.js
promort/src/js/worklist/worklist.controllers.js
promort/static/templates/dialogs/clinical_step_cant_start.html
promort/static/templates/dialogs/reopen_rois_step_failed.html

Fixing ROIs annotation steps reopen

---

promort/slides_manager/management/commands/get_labs_info.py
promort/slides_manager/management/commands/link_cases_to_lab.py

Improved association tool and added a tool to get a quick report

Improved cases to labs link

---

promort/odin/views/review_results.py

Fixed the algorithm to calculate the score of the "final" review of a given case

Fixing API used to calculate case scoring

---

promort/src/js/clinical_annotations_manager/clinical_annotations_manager.controllers.js
promort/src/js/clinical_annotations_manager/clinical_annotations_manager.directives.js
promort/src/js/rois_manager/rois_manager.controllers.js
promort/static/css/promort.css
promort/static/templates/clinical_annotations_manager/core_annotation.html
promort/static/templates/clinical_annotations_manager/focus_region_annotation.html
promort/static/templates/clinical_annotations_manager/manager.html
promort/static/templates/slide_review/quality_control.html

Added units of measure selectors to core and focus region clinical annotation interface

Minor improvements in user interface

---

promort/src/js/clinical_annotations_manager/clinical_annotations_manager.controllers.js
promort/static/templates/dialogs/accept_clinical_annotation_confirm.html

Only positive cores annotation is now mandatory

Losened constraints to close clinical annotations

---

promort/clinical_annotations_manager/serializers.py
promort/clinical_annotations_manager/views.py
promort/src/js/clinical_annotations_manager/clinical_annotations_manager.controllers.js
promort/src/js/ome_seadragon_viewer/viewer.services.js
promort/src/js/rois_manager/rois_manager.controllers.js
promort/static/css/promort.css
promort/static/templates/clinical_annotations_manager/focus_region_annotation.html
promort/static/templates/rois_manager/core.html
promort/static/templates/rois_manager/focus_region.html
promort/static/templates/rois_manager/slice.html

For further details on new tools check
https://github.com/crs4/ome_seadragon/pull/42

Integrating new version of ome_seadragon freehand drawing tool

---

promort/odin/views/__init__.py
promort/odin/views/rois_extraction.py
promort/promort/urls.py

New HTTP methods for data extraction using odin framework

New HTTP methods for data extraction

---

promort/clinical_annotations_manager/management/commands/get_cores_clinical_data.py
promort/clinical_annotations_manager/management/commands/get_focus_regions_clinical_data.py
promort/clinical_annotations_manager/management/commands/get_slices_clinical_data.py
promort/clinical_annotations_manager/models.py
promort/odin/views/rois_extraction.py
promort/reviews_manager/management/commands/get_clinical_annotation_steps_data.py
promort/reviews_manager/models.py
promort/rois_manager/management/commands/get_cores_data.py
promort/rois_manager/management/commands/get_focus_regions_data.py
promort/rois_manager/management/commands/get_slices_data.py
promort/slides_manager/management/commands/get_cases_data.py
promort/slides_manager/management/commands/get_slides_data.py
promort/slides_manager/management/commands/get_slides_evaluation_data.py

Data export

---

promort/odin/views/__init__.py
promort/odin/views/reviewers_report.py
promort/promort/urls.py
promort/reviews_manager/models.py
promort/templates/annotations_report.txt

Send a report about the status of the reviews as an email with attached CSV files

Reviews status report

---

promort/reviews_manager/management/commands/build_rois_reviews_worklist.py
promort/rois_manager/management/commands/dump_rois.py
promort/rois_manager/management/commands/extract_cores.py
promort/rois_manager/management/commands/extract_focus_regions.py
promort/rois_manager/management/commands/restore_rois.py
requirements_server.txt

Fixed focus regions export tool

Focus regions as JSON

---

promort/reviews_manager/management/commands/reopen_clinical_annotation_steps.py
promort/reviews_manager/models.py

Tool to quickly reopen clinical annotation steps and, optionally, change assigned reviewer

Reopen clinical annotations

---

promort/clinical_annotations_manager/models.py
promort/clinical_annotations_manager/serializers.py
promort/rois_manager/models.py
promort/src/js/clinical_annotations_manager/clinical_annotations_manager.controllers.js
promort/static_src/templates/clinical_annotations_manager/slice_annotation.html

* New formula for Gleason 4 % in core panels
* Added Gleason 4 % to slice panels

Updated Gleason 4 percentage

---

promort/authentication/views.py
promort/promort/urls.py
promort/src/js/authentication/authentication.controllers.js
promort/src/js/authentication/authentication.services.js
promort/src/js/promort.routes.js
promort/static_src/css/promort.css
promort/static_src/templates/authentication/change_password.html
promort/static_src/templates/dialogs/old_password_check_error.html
promort/static_src/templates/dialogs/password_update_success.html
promort/static_src/templates/dialogs/updating_password.html
promort/templates/navbar.html

Users can now change their own password once logged into the system

Password change

---

promort/promort/urls.py
promort/rois_manager/views.py

ROIs retrieval API
